
default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['SFOOTY_DATABASE_USERNAME'] %>
  password: <%= ENV['SFOOTY_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: SFooty_development

test:
  <<: *default
  database: SFooty_test

production:
  <<: *default
  database: SFooty_production
  username: SFooty
  password: <%= ENV["SFOOTY_DATABASE_PASSWORD"] %>
